# Generated by Django 3.0 on 2019-12-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='categoryname',
        ),
    ]
