# Generated by Django 3.0 on 2019-12-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0002_auto_20191217_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryname',
            new_name='category_name',
        ),
    ]
